### ISSUE TITLE
An Issue for Mark Schwartz to move to in-progress, then Close

### ISSUE THREAD

**Issue by worthp** [olentangyfrc/2018-off-season#20]
Hey Mark, move this card to in-progress. Then click the link and see if you can Close it. When you close it, it will automatically move to the Done column.

**Comment by schwartz3** [comment]
It looks like permissions don't allow me to edit this issue.  According to this link:  https://guides.github.com/features/issues/ I should see an edit button just to the left of 'new issue'.  I do not.  Can you take a look?

**Comment by schwartz3** [comment]
closed
