### ISSUE TITLE
New member meeting

### ISSUE THREAD

**Issue by sethstobart** [olentangyfrc/2018-off-season#30]
Incomplete:
Update website with date info
Post flier around all four schools
Contact news at all four schools

Complete:
Presentation
Create the flier for meeting

**Comment by sethstobart** [comment]
Presentation: https://docs.google.com/presentation/d/1i3QCKGmrjYrrUqo6W_T7BDG8C5Hdq9VhrlmbO5qjV4g/edit?usp=sharing

**Comment by Eiim** [comment]
What is the date info?

**Comment by sethstobart** [comment]
schmidt is working on it/maybe has it figured out by now
