### ISSUE TITLE
New 3D printer functioning

### ISSUE THREAD

**Issue by sethstobart** [olentangyfrc/2018-off-season#32]

**Comment by Eiim** [comment]
We should be able to reuse for now until we figure out if that's a problem.
For test prints it shouldn't be. Wasn't Olentangy going to try that out?

**Comment by olentangyfrcowner** [comment]
From my understanding you cannot re-use plates, unless we have figured out a hack.  I will touch base with OHS.

**Comment by Eiim** [comment]
Closing because done. Grilled and Cheese are nicely operational.
