### ISSUE TITLE
NASA Grant

### ISSUE THREAD

**Issue by sethstobart** [olentangyfrc/2018-off-season#33]
https://frc-grants.arc.nasa.gov/rcs/directions.php?utm_campaign=fr-team-blast-019&utm_source=hs_email&utm_medium=email&utm_content=65742986&_hsenc=p2ANqtz-8JMG6DbFHAvZSZmsa4sUXk97uxQqAQMsaLS3y1uZc9o1wAiIBgGLrcOAbUk0bAfJEph3aKbssXCUelxvvZUct4dpNKYw&_hsmi=65742986

**Comment by olentangyfrcowner** [comment]
Wasn't there one last item to complete with this grant?

**Comment by sethstobart** [comment]
The email from Mr. Smith, he sent it to them. You're CC'd on the email @olentangyfrcowner
