### ISSUE TITLE
Grad Cords

### ISSUE THREAD

**Issue by sethstobart** [olentangyfrc/2018-off-season#35]
https://docs.google.com/document/d/1D2k_xbNDcCbB1rA2nGtGvG0_3QCCbbDfr5PM2AHEgsw/edit?usp=sharing

**Comment by sethstobart** [comment]
@olentangyfrcowner should we send these answers to Mr. Smith now?

**Comment by olentangyfrcowner** [comment]
Proposal is in Mr. Smith's mailbox.
